2024-07-24 11:40:30.033 | SUCCESS  | __main__:check_url_status:102 - URL is reachable: http://instagram.com
2024-07-24 11:40:52.955 | SUCCESS  | __main__:check_url_status:102 - URL is reachable: http://facebook.com
2024-07-24 11:40:55.969 | SUCCESS  | __main__:check_url_status:102 - URL is reachable: http://youtube.com
2024-07-24 11:40:59.002 | SUCCESS  | __main__:check_url_status:102 - URL is reachable: http://instagram.com
2024-07-24 11:41:02.068 | SUCCESS  | __main__:check_url_status:102 - URL is reachable: http://olx.ba
2024-07-24 11:41:06.199 | SUCCESS  | __main__:check_url_status:102 - URL is reachable: https://vaktija.ba/
2024-07-24 11:41:36.099 | ERROR    | __main__:check_url_status:113 - An error occurred while checking URL https://asdasda.com: HTTPSConnectionPool(host='asdasda.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002596E3E61B0>, 'Connection to asdasda.com timed out. (connect timeout=10)'))
2024-07-24 11:42:02.947 | SUCCESS  | __main__:check_url_status:102 - URL is reachable: https://vaktija.ba/
